import Head from 'next/head'
import MentalFlashCard from "../pages/Flashcards/MentalFlashCard"
import styles from '../styles/Home.module.css'
import ListOfQuestions from "../pages/data/ListOfQuestions.json";
import InputFlashCard from "../pages/Flashcards/InputFlashCard";
import { NextPage } from 'next';
import Layout from '../components/Layout';
import Link from 'next/link';

const Home: NextPage = () => {
  return (
    <>
    <Layout>
    <div className={styles.container}>
      <Head>
        <title>FlashCard Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to my Flashcard website
          </h1>
          <div>
            <Link href="/Flashcards/MentalFlashCard">MentalFlashCard </Link>
          </div>
          <div>
            <Link href="/Flashcards/InputFlashCard">InputFlashCard </Link>
          </div>
          <div>
            <Link href="/Flashcards/MultipleFlashCard">MultipleFlashCard </Link>
          </div>
      </main>
    </div> 
    </Layout>
    </>
  )
}
    

export default Home;